# This is a Github Workflow that runs tests on any push or pull request.
# If the tests pass and this is a push to the master branch it also runs Semantic Release.
name: CI
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkuout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Yarn install
        run: yarn

      - name: Build
        run: yarn build

      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          path: |
            docs
            target
            flow-typed
            typings
            buildstamp.json

  # Fast unit tests flow
  test_push:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkuout
        uses: actions/checkout@v3

      - name: Restore artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Yarn install
        run: yarn

      - name: Unit test only
        run: yarn test:unit

      - name: Update coverage
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          path: |
            coverage
            .nyc_output

  # Full tests for PR
  test_pr:
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-22.04 ]
        node-version: [ 14, 18, 20 ]

    name: Test (Node v${{ matrix.node-version }}, OS ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
      - name: Checkuout
        uses: actions/checkout@v3

      - name: Restore artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn install
        run: yarn --ignore-engines

      - name: Unit test
        if: matrix.node-version != '18' || matrix.os != 'ubuntu-22.04'
        run: yarn test:unit

      # Run all tests for Ubuntu + NodeJS v14 only
      - name: Full test suite
        if: matrix.node-version == '18' && matrix.os == 'ubuntu-22.04'
        run: yarn test

  release:
    name: Release
    # https://github.community/t/trigger-job-on-tag-push-only/18076
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    needs: test_push
    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkuout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact-${{ github.run_id }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Codeclimate
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageLocations: |
            ${{ github.workspace }}/coverage/lcov.info:lcov

      - name: Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_PROVENANCE: true
          GH_USER: '@antongolub'
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: 'antongolub@antongolub.ru'
          GIT_COMMITTER_EMAIL: 'antongolub@antongolub.ru'
          GIT_AUTHOR_NAME: 'Anton Golub'
          GIT_COMMITTER_NAME: 'Anton Golub'
        run: npm_config_yes=true npx zx-semrel

